name: CI Linux (i686)

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.libretro.com:5050/libretro-infrastructure/libretro-build-i386-ubuntu:xenial-gcc9
      options: --user root

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Compile b2-libretro
        run: |
          cd src/libretro
          make -j$(getconf _NPROCESSORS_ONLN) clean
          make -j$(getconf _NPROCESSORS_ONLN)

